version: "3.9"
name: bookstore
services:
  api:
    container_name: bookstore-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["sh", "-c", "node ace migration:run --force && node ./bin/server.js"]
    ports:
      - 8080:8080
    env_file:
      - .env
  db:
    container_name: bookstore-db
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./bookstore-db:/var/lib/postgresql/data
  db-hom:
    container_name: bookstore-db-hom
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"