import Book from '#models/book'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { BookCategoryEnum } from '../../app/enums/BookCategoryEnum.js'

export default class extends BaseSeeder {
  async run() {
    await Book.createMany([
      {
        title: 'A Brief History of Time',
        author: 'Stephen Hawking',
        description: 'A landmark volume in science writing by one of the great minds of our time.',
        stock: 12,
        price: 4590,
        imageURL: 'https://example.com/images/brief-history.jpg',
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Selfish Gene',
        author: 'Richard Dawkins',
        stock: 8,
        price: 3999,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Bible',
        author: 'Various Authors',
        description: 'Sacred scripture in Christianity, containing the Old and New Testaments.',
        stock: 100,
        price: 2999,
        imageURL: 'https://example.com/images/bible.jpg',
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Cosmos',
        author: 'Carl Sagan',
        stock: 5,
        price: 4999,
        imageURL: 'https://example.com/images/cosmos.jpg',
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Origin of Species',
        author: 'Charles Darwin',
        stock: 10,
        price: 4250,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Genesis',
        author: 'Moses',
        description: 'The first book of the Bible.',
        stock: 50,
        price: 999,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Sapiens: A Brief History of Humankind',
        author: 'Yuval Noah Harari',
        stock: 20,
        price: 5990,
        imageURL: 'https://example.com/images/sapiens.jpg',
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Book of Psalms',
        author: 'David',
        stock: 30,
        price: 1499,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Thinking, Fast and Slow',
        author: 'Daniel Kahneman',
        stock: 9,
        price: 5200,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Book Thief',
        author: 'Markus Zusak',
        stock: 7,
        price: 3500,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Ecclesiastes',
        author: 'Solomon',
        stock: 25,
        price: 1100,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Astrophysics for People in a Hurry',
        author: 'Neil deGrasse Tyson',
        stock: 15,
        price: 3799,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Romans',
        author: 'Paul',
        stock: 40,
        price: 1050,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'The Martian',
        author: 'Andy Weir',
        stock: 14,
        price: 4400,
        imageURL: 'https://example.com/images/martian.jpg',
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Exodus',
        author: 'Moses',
        stock: 20,
        price: 1299,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'A Short History of Nearly Everything',
        author: 'Bill Bryson',
        stock: 11,
        price: 4875,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Brave New World',
        author: 'Aldous Huxley',
        stock: 16,
        price: 3950,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Leviticus',
        author: 'Moses',
        stock: 33,
        price: 1325,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'The Elegant Universe',
        author: 'Brian Greene',
        stock: 6,
        price: 5000,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Numbers',
        author: 'Moses',
        stock: 22,
        price: 1175,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Fahrenheit 451',
        author: 'Ray Bradbury',
        stock: 10,
        price: 3099,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'The Grand Design',
        author: 'Stephen Hawking',
        stock: 7,
        price: 4725,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Deuteronomy',
        author: 'Moses',
        stock: 20,
        price: 1249,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: '1984',
        author: 'George Orwell',
        stock: 13,
        price: 3190,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Black Holes and Baby Universes',
        author: 'Stephen Hawking',
        stock: 4,
        price: 3895,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Book of Revelation',
        author: 'John',
        stock: 19,
        price: 1499,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        stock: 18,
        price: 2899,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'The Universe in a Nutshell',
        author: 'Stephen Hawking',
        stock: 5,
        price: 5325,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'The Gospel of John',
        author: 'John',
        stock: 27,
        price: 995,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        stock: 14,
        price: 2799,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'The Structure of Scientific Revolutions',
        author: 'Thomas S. Kuhn',
        stock: 6,
        price: 4600,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Galatians',
        author: 'Paul',
        stock: 31,
        price: 1020,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Slaughterhouse-Five',
        author: 'Kurt Vonnegut',
        stock: 9,
        price: 3400,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Silent Spring',
        author: 'Rachel Carson',
        stock: 8,
        price: 4000,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Acts of the Apostles',
        author: 'Luke',
        stock: 23,
        price: 1290,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Moby-Dick',
        author: 'Herman Melville',
        stock: 6,
        price: 3675,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'The Demon-Haunted World',
        author: 'Carl Sagan',
        stock: 7,
        price: 4560,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Hebrews',
        author: 'Paul',
        stock: 28,
        price: 1125,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        stock: 15,
        price: 3330,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'Gödel, Escher, Bach',
        author: 'Douglas Hofstadter',
        stock: 3,
        price: 5690,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Proverbs',
        author: 'Solomon',
        stock: 36,
        price: 1099,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        stock: 12,
        price: 4199,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'The Immortal Life of Henrietta Lacks',
        author: 'Rebecca Skloot',
        stock: 10,
        price: 3980,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Isaiah',
        author: 'Isaiah',
        stock: 30,
        price: 1330,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Don Quixote',
        author: 'Miguel de Cervantes',
        stock: 5,
        price: 4410,
        category: BookCategoryEnum.OTHERS,
      },
      {
        title: 'On the Origin of Time',
        author: 'Thomas Hertog',
        stock: 4,
        price: 5120,
        category: BookCategoryEnum.SCIENCE,
      },
      {
        title: 'Matthew',
        author: 'Matthew',
        stock: 24,
        price: 1190,
        category: BookCategoryEnum.BIBLE,
      },
      {
        title: 'Frankenstein',
        author: 'Mary Shelley',
        stock: 13,
        price: 3245,
        category: BookCategoryEnum.OTHERS,
      },
    ])
  }
}
